import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'fs-extra';
import path from 'path';
import { sanitizeAiSlop, AI_SLOP_PATTERNS } from '../src/core/sanitize/aiSlopSanitizer.js';

const SLOP_TEST_DIR = path.join(process.cwd(), 'tests', 'fixtures', 'slop-test-dir');

describe('AI Slop & Watermark Sanitizer', () => {
  beforeEach(async () => {
    await fs.ensureDir(SLOP_TEST_DIR);

    // TypeScript file with agent comments and fake sleep delay
    const tsCode = `// Generated by Claude 3.5 Sonnet
import express from 'express';

// Cursor Rule: Always check authentication
export async function handleRequest() {
  // In a production environment, you should replace this mock with real database
  await new Promise(r => setTimeout(r, 1000));
  // Mock response for demo purposes
  return { status: "ok" };
}
`;
    await fs.writeFile(path.join(SLOP_TEST_DIR, 'service.ts'), tsCode);

    // Python file with AI slop
    const pyCode = `# Generated by ChatGPT
import os

# Note: In a production app, you should use environment variables
def get_llm():
    # CoT: Step 1: Initialize model
    return "gpt-4o"
`;
    await fs.writeFile(path.join(SLOP_TEST_DIR, 'agent.py'), pyCode);
  });

  afterEach(async () => {
    await fs.remove(SLOP_TEST_DIR);
  });

  it('should detect and remove all AI agent signatures and lazy comments', async () => {
    const result = await sanitizeAiSlop({
      rootDir: SLOP_TEST_DIR,
      removeMockDelays: true
    });

    expect(result.totalSlopRemoved).toBeGreaterThanOrEqual(6);
    expect(result.modifiedFiles).toContain('service.ts');
    expect(result.modifiedFiles).toContain('agent.py');

    const cleanTs = await fs.readFile(path.join(SLOP_TEST_DIR, 'service.ts'), 'utf-8');
    expect(cleanTs).not.toContain('Generated by Claude');
    expect(cleanTs).not.toContain('Cursor Rule');
    expect(cleanTs).not.toContain('In a production environment');
    expect(cleanTs).not.toContain('Mock response for demo');
    expect(cleanTs).not.toContain('setTimeout(r, 1000)');

    const cleanPy = await fs.readFile(path.join(SLOP_TEST_DIR, 'agent.py'), 'utf-8');
    expect(cleanPy).not.toContain('Generated by ChatGPT');
    expect(cleanPy).not.toContain('CoT: Step 1');
  });

  it('should support dryRun without altering files', async () => {
    const result = await sanitizeAiSlop({
      rootDir: SLOP_TEST_DIR,
      dryRun: true
    });

    expect(result.totalSlopRemoved).toBeGreaterThan(0);
    const ts = await fs.readFile(path.join(SLOP_TEST_DIR, 'service.ts'), 'utf-8');
    expect(ts).toContain('Generated by Claude');
  });
});
