import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'fs-extra';
import path from 'path';
import { shipAI } from '../src/sdk/index.js';

const SDK_TEST_DIR = path.join(process.cwd(), 'tests', 'fixtures', 'sdk-test-dir');

describe('ShipAI Programmatic SDK', () => {
  beforeEach(async () => {
    await fs.ensureDir(SDK_TEST_DIR);
    await fs.writeJson(path.join(SDK_TEST_DIR, 'package.json'), {
      name: 'prototype-agent',
      version: '0.1.0',
      dependencies: {
        express: '^4.18.2'
      },
      scripts: {
        start: 'node index.js'
      }
    });

    await fs.writeFile(
      path.join(SDK_TEST_DIR, 'index.js'),
      `// Generated by Claude 3.5 Sonnet
const express = require('express');
const app = express();
// Note: In production you should implement authentication
app.get('/api/prototype-agent', (req, res) => res.json({ name: 'prototype-agent' }));
app.listen(3000);
`
    );
  });

  afterEach(async () => {
    for (let i = 0; i < 3; i++) {
      try {
        await fs.remove(SDK_TEST_DIR);
        break;
      } catch {
        await new Promise(r => setTimeout(r, 100));
      }
    }
  });

  it('should run end-to-end transformation via unified shipAI() SDK call', async () => {
    const summary = await shipAI({
      rootDir: SDK_TEST_DIR,
      sourceName: 'PrototypeAgent',
      targetName: 'OmniDeskAI',
      clientName: 'Apex Global',
      brandColor: '#0ea5e9',
      modules: {
        audit: true,
        sanitize: true,
        cleanAiSlop: true,
        rebrand: true,
        pack: true,
        docker: true,
        universalGateway: true,
        guardrails: true,
        diagnostics: true,
        costReport: true,
        verify: true
      }
    });

    expect(summary.targetName).toBe('OmniDeskAI');
    expect(summary.clientName).toBe('Apex Global');
    expect(summary.shipScore).toBeGreaterThanOrEqual(80);
    expect(summary.docsCreated).toContain('README.md');
    expect(summary.docsCreated).toContain('DELIVERY_CERTIFICATE.md');
    expect(summary.docsCreated).toContain('WARRANTY_AND_IP_CLEARANCE.md');
    expect(summary.docsCreated).toContain('CLIENT_DEMO_SCRIPT.md');
    expect(summary.docsCreated).toContain('AI_SYSTEM_CARD.md');
    expect(summary.docsCreated).toContain('AI_COST_AND_SCALING_PROJECTION.md');

    // Verify AI comment was sanitized
    const code = await fs.readFile(path.join(SDK_TEST_DIR, 'index.js'), 'utf-8');
    expect(code).not.toContain('Generated by Claude');
    expect(code).not.toContain('prototype-agent');
    expect(code).toContain('omni-desk-ai');

    // Verify docker and diagnostics files exist
    expect(await fs.pathExists(path.join(SDK_TEST_DIR, 'Dockerfile'))).toBe(true);
    expect(await fs.pathExists(path.join(SDK_TEST_DIR, 'docker-compose.yml'))).toBe(true);
    expect(await fs.pathExists(path.join(SDK_TEST_DIR, 'scripts', 'client-diagnostics.mjs'))).toBe(true);
  });
});
