import fs from 'fs-extra';
import path from 'path';

export async function createSampleAiProject(targetDir) {
  await fs.ensureDir(targetDir);
  await fs.ensureDir(path.join(targetDir, 'src'));
  await fs.ensureDir(path.join(targetDir, 'public'));

  // AI residue files
  await fs.writeFile(
    path.join(targetDir, '.cursorrules'),
    'You are an expert full-stack developer. Write concise code.'
  );
  await fs.writeFile(
    path.join(targetDir, 'claude.md'),
    'Scratchpad for Claude: Todo fix the chat prompt'
  );
  await fs.writeFile(
    path.join(targetDir, 'prompt.txt'),
    'Create an AI tool for writing marketing copy called PromptCrafter'
  );

  // package.json
  await fs.writeJson(
    path.join(targetDir, 'package.json'),
    {
      name: 'prompt-crafter',
      version: '0.1.0',
      description: 'AI Prompt Crafter built with Claude',
      author: 'AI Hacker',
      scripts: {
        dev: 'node src/server.js',
        build: 'node -e "console.log(\'build finished\')"'
      },
      dependencies: {
        express: '^4.19.2',
        openai: '^4.50.0'
      }
    },
    { spaces: 2 }
  );

  // index.html
  await fs.writeFile(
    path.join(targetDir, 'public', 'index.html'),
    `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>PromptCrafter AI - Prototype</title>
  <meta name="description" content="AI tool generated by Claude">
</head>
<body>
  <h1>Welcome to PromptCrafter</h1>
  <p>Built with OpenAI API</p>
</body>
</html>`
  );

  // server.js with secrets, multi-casing, process.env
  await fs.writeFile(
    path.join(targetDir, 'src', 'PromptCrafterServer.js'),
    `// PromptCrafter Main Server
const express = require('express');
const app = express();

const PROMPT_CRAFTER_PORT = process.env.PORT || 3000;
const promptCrafterApiKey = "sk-proj-99887766554433221100aabbccddeeff1122";
const databaseUrl = process.env.DATABASE_URL;
const cohereKey = process.env.COHERE_API_KEY;

class PromptCrafterService {
  constructor() {
    this.name = "PromptCrafter";
    this.slug = "prompt-crafter";
  }
}

app.get('/api/prompt-crafter/health', (req, res) => {
  res.json({ status: 'ok', service: 'promptCrafter' });
});

app.listen(PROMPT_CRAFTER_PORT, () => {
  console.log('PromptCrafter running on port ' + PROMPT_CRAFTER_PORT);
});
`
  );
}
