export const AI_RESIDUE_FILES = [
  '.cursorrules',
  '.windsurfrules',
  '.copilot-instructions.md',
  '.aider.chat.history.md',
  '.aider.tags.cache.v3',
  '.aider.input.history',
  'claude.md',
  'CLAUDE.md',
  'prompt.txt',
  'prompts.txt',
  'ai-prompt.txt',
  'ai-instructions.md',
  'system-prompt.txt',
  'llm_scratchpad.txt',
  'scratchpad.md',
  '.chatgpt',
  'agent_output.log',
  'agent-scratchpad.txt'
];

export const AI_RESIDUE_DIRS = [
  '.cursor',
  '.windsurf',
  '.v0',
  '.aider',
  '.chatgpt'
];

export const IGNORE_PATTERNS = [
  '**/node_modules/**',
  '**/.git/**',
  '**/dist/**',
  '**/build/**',
  '**/.next/**',
  '**/.nuxt/**',
  '**/.turbo/**',
  '**/coverage/**',
  '**/.cache/**',
  '**/package-lock.json',
  '**/pnpm-lock.yaml',
  '**/yarn.lock',
  '**/bun.lockb',
  '**/*.png',
  '**/*.jpg',
  '**/*.jpeg',
  '**/*.gif',
  '**/*.webp',
  '**/*.ico',
  '**/*.pdf',
  '**/*.zip',
  '**/*.tar.gz',
  '**/*.woff',
  '**/*.woff2',
  '**/*.ttf',
  '**/*.eot',
  '**/*.mp4',
  '**/*.webm',
  '**/*.mp3',
  '**/*.wasm'
];

export const SECRET_PATTERNS = [
  {
    name: 'OpenAI API Key',
    regex: /sk-[a-zA-Z0-9_-]{20,}/g,
    mask: (key: string) => `${key.substring(0, 7)}...${key.substring(key.length - 4)}`
  },
  {
    name: 'Anthropic Claude API Key',
    regex: /sk-ant-[a-zA-Z0-9_-]{20,}/g,
    mask: (key: string) => `${key.substring(0, 10)}...${key.substring(key.length - 4)}`
  },
  {
    name: 'Groq API Key',
    regex: /gsk_[a-zA-Z0-9]{20,}/g,
    mask: (key: string) => `${key.substring(0, 7)}...${key.substring(key.length - 4)}`
  },
  {
    name: 'HuggingFace Access Token',
    regex: /hf_[a-zA-Z0-9]{34,}/g,
    mask: (key: string) => `${key.substring(0, 6)}...${key.substring(key.length - 4)}`
  },
  {
    name: 'AWS Access Key ID',
    regex: /AKIA[0-9A-Z]{16}/g,
    mask: (key: string) => `${key.substring(0, 8)}...`
  },
  {
    name: 'Supabase JWT / Secret',
    regex: /eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+/g,
    mask: (key: string) => `${key.substring(0, 15)}...${key.substring(key.length - 6)}`
  },
  {
    name: 'Generic API Key / Secret',
    regex: /(?:api[_-]?key|secret|token|password|auth_token)\s*[:=]\s*['"]([a-zA-Z0-9_\-\.]{20,})['"]/gi,
    mask: (_full: string, key?: string) => `***REDACTED_${key ? key.substring(0, 4) : 'SECRET'}***`
  }
];

export const AI_WATERMARK_STRINGS = [
  'created by v0',
  'built with bolt.new',
  'generated by gpt',
  'generated by chatgpt',
  'claude code',
  'claude artifact',
  'cursor ai',
  'windsurf cascade',
  'prompt engineer',
  'replace with your openai api key',
  'as an ai language model',
  'insert your api key here'
];
