import { getProjectFiles, readTextFile, writeTextFile } from '../../utils/fileUtils.js';
import { computeUnifiedDiff, FileDiff } from '../diff/diffInspector.js';

export interface SlopPattern {
  name: string;
  regex: RegExp;
  category: 'agent-watermark' | 'lazy-comment' | 'mock-delay' | 'disclaimer';
}

export const AI_SLOP_PATTERNS: SlopPattern[] = [
  // Agent Watermarks & Generated-by Tags
  {
    name: 'Claude Generation Comment',
    regex: /\/\/\s*(?:Generated by|Created with|Prompt:?)\s*(?:Claude|Anthropic|Sonnet|Opus|Haiku)[^\r\n]*/gi,
    category: 'agent-watermark'
  },
  {
    name: 'ChatGPT / OpenAI Generation Comment',
    regex: /\/\/\s*(?:Generated (?:by|with)|Created with)\s*(?:ChatGPT|GPT-4o?|OpenAI|Chat-GPT)[^\r\n]*/gi,
    category: 'agent-watermark'
  },
  {
    name: 'Cursor AI Comment',
    regex: /\/\/\s*(?:Created with Cursor|Cursor Rule:?|Generated by Cursor)[^\r\n]*/gi,
    category: 'agent-watermark'
  },
  {
    name: 'Windsurf Cascade Block',
    regex: /\/\*\s*windsurf:(?:start|end)\s*\*\/|\/\/\s*Windsurf Cascade[^\r\n]*/gi,
    category: 'agent-watermark'
  },
  {
    name: 'v0 by Vercel Comment',
    regex: /\/\*\s*v0 by Vercel\s*\*\/|\/\/\s*(?:Created with|Generated by)\s*v0[^\r\n]*/gi,
    category: 'agent-watermark'
  },
  {
    name: 'Lovable / Bolt Watermarks',
    regex: /<!--\s*Lovable\s*-->|\/\/\s*(?:Created with|Generated by)\s*(?:Lovable|Bolt\.new)[^\r\n]*/gi,
    category: 'agent-watermark'
  },
  {
    name: 'Devin / Aider / Copilot Watermarks',
    regex: /\/\/\s*(?:Generated by Devin|Aider suggested|GitHub Copilot suggested)[^\r\n]*/gi,
    category: 'agent-watermark'
  },
  // Python Hash Comments
  {
    name: 'Python AI Generation Comment',
    regex: /#\s*(?:Generated by|Created with)\s*(?:Claude|ChatGPT|Cursor|Windsurf|OpenAI|Gemini|Devin)[^\r\n]*/gi,
    category: 'agent-watermark'
  },

  // AI Lazy Comments & Hallmarks
  {
    name: 'Production Disclaimer Comment',
    regex: /(?:\/\/|#)\s*(?:Note:\s*)?In (?:a )?production (?:environment|app),?\s*(?:you should|replace this with|implement real)[^\r\n]*/gi,
    category: 'lazy-comment'
  },
  {
    name: 'Mock Implementation Disclaimer',
    regex: /(?:\/\/|#)\s*Mock (?:implementation|data|response) for (?:demo|demonstration|testing) purposes?[^\r\n]*/gi,
    category: 'lazy-comment'
  },
  {
    name: 'Chain of Thought / Step Comment',
    regex: /(?:\/\/|#)\s*(?:CoT:|Step \d+:|Let me know if you have questions|Hope this helps!)[^\r\n]*/gi,
    category: 'lazy-comment'
  },
  {
    name: 'Python Production Disclaimer',
    regex: /#\s*(?:Note:\s*)?In (?:a )?production (?:environment|app),?\s*(?:you should|replace this with)[^\r\n]*/gi,
    category: 'lazy-comment'
  },

  // Artificial AI Sleep / Delay Hacks
  {
    name: 'Artificial AI Mock Delay Hack',
    regex: /await\s+new\s+Promise\s*\(\s*(?:\([a-zA-Z0-9_]+\)|[a-zA-Z0-9_]+)\s*=>\s*setTimeout\s*\(\s*[a-zA-Z0-9_]+,\s*(?:[5-9]\d{2}|[1-9]\d{3,4})\s*\)\s*\);?/g,
    category: 'mock-delay'
  }
];

export interface CleanSlopOptions {
  rootDir: string;
  removeMockDelays?: boolean;
  dryRun?: boolean;
}

export interface SlopFinding {
  filePath: string;
  relativePath: string;
  patternName: string;
  category: string;
  line: number;
  matchedText: string;
}

export interface CleanSlopResult {
  totalFilesScanned: number;
  totalFilesModified: number;
  totalSlopRemoved: number;
  findings: SlopFinding[];
  modifiedFiles: string[];
  diffs: FileDiff[];
}

/**
 * Scans and purges AI agent comment watermarks, lazy disclaimers, and hacky simulated sleep delays
 */
export async function sanitizeAiSlop(options: CleanSlopOptions): Promise<CleanSlopResult> {
  const { rootDir, removeMockDelays = true, dryRun = false } = options;

  const files = await getProjectFiles(rootDir);
  const eligibleExtensions = /\.(ts|tsx|js|jsx|mjs|cjs|py|html|vue|svelte|css|json|md)$/i;

  const findings: SlopFinding[] = [];
  const modifiedFiles: string[] = [];
  const diffs: FileDiff[] = [];
  let totalSlopRemoved = 0;

  for (const file of files) {
    if (!eligibleExtensions.test(file.filePath)) continue;
    if (file.relativePath.includes('node_modules') || file.relativePath.includes('.git')) continue;

    let content: string;
    try {
      content = await readTextFile(file.filePath);
    } catch {
      continue;
    }

    let updated = content;
    let fileModified = false;

    for (const pattern of AI_SLOP_PATTERNS) {
      if (pattern.category === 'mock-delay' && !removeMockDelays) {
        continue;
      }

      pattern.regex.lastIndex = 0;
      let match: RegExpExecArray | null;

      while ((match = pattern.regex.exec(content)) !== null) {
        const matchedText = match[0];
        const line = content.substring(0, match.index).split('\n').length;

        findings.push({
          filePath: file.filePath,
          relativePath: file.relativePath,
          patternName: pattern.name,
          category: pattern.category,
          line,
          matchedText: matchedText.trim()
        });

        // Replace matched slop
        if (pattern.category === 'mock-delay') {
          // Replace artificial sleep with a clean no-op comment
          updated = updated.replace(matchedText, '/* shipai: mock delay removed for instant client response */');
        } else {
          // Remove comment line cleanly
          updated = updated.replace(matchedText, '');
        }

        totalSlopRemoved++;
        fileModified = true;
      }
    }

    // Clean up empty lines left behind by comment removal
    if (fileModified) {
      updated = updated.replace(/^[ \t]*\r?\n[ \t]*\r?\n/gm, '\n');

      if (updated !== content) {
        modifiedFiles.push(file.relativePath);
        const diff = computeUnifiedDiff(file.relativePath, content, updated);
        if (diff) {
          diffs.push(diff);
        }

        if (!dryRun) {
          await writeTextFile(file.filePath, updated);
        }
      }
    }
  }

  return {
    totalFilesScanned: files.length,
    totalFilesModified: modifiedFiles.length,
    totalSlopRemoved,
    findings,
    modifiedFiles,
    diffs
  };
}
